### ISSUE TITLE
audio is not playing in the viewer

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-collection-viewer#10] opened 2016-06-15 07:17 UTC
The screen ends with 'Loading media... please wait.'. Also reported by other users. In both the test viewer and the current viewer. I'm not sure if this is a viewer issue or for Terem to deal with, but the media plays fine in NABU.

**Comment by MLR-au** [comment] 2016-07-11 11:15
Item / Collection? Which media file? Might be an format unsupported by the viewer (it has a whitelist) or something else.

**Comment by nthieberger** [comment] 2016-07-12 01:27
I think this was actually an issue related to a user not being logged in but trying to play media. Hence the need for a message to the user telling them they need to log in

**Comment by MLR-au** [comment] 2016-07-16 21:55
Closed as a duplicate of #11

**Closed by MLR-au** 2016-07-16 21:55 UTC
Labels: bug
